import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { PassiveSocketProvider } from "@/context/passive-socket-context";
import SessionProvider from "@/context/session-context";
import { getUserInfo } from "@/actions/user-actions/get-user-info";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "omegalol",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const user = await getUserInfo();
  

  return (
    <html lang="en" className="h-full">
      <body className={`${roboto.variable} ${roboto.variable} antialiased h-full`}>
          <PassiveSocketProvider>
            <SessionProvider initialSession={user}>
            {children}

            </SessionProvider>
          </PassiveSocketProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
